### ISSUE TITLE
Radio controlled "silver key" car screen stays at white noise

### ISSUE THREAD

**Issue by BenjiClub** [jonof/jfsw#11]
At the spot in Level 1 where you have to navigate the radio controlled car with the silver wagon the screen for the camera simply stays at white noise. You have to set back to 8 bit mode and steer the wagon to the "player accessible spot".

In high color mode the remote control screen doesn't update.

It sometimes updates, but then you see only one picture and it freezes.

**Comment by jonof** [comment]
Yeah, this has been a fault for a long time. The last time I investigated it, which was a great many years ago, I think it was due to the wall behind the viewscreen sprite being considered 'unseen' during visibility processing. I'd have to recheck though.
