### ISSUE TITLE
(Linux) GTK throws segmentation at start up

### ISSUE THREAD

**Issue by BenjiClub** [jonof/jfsw#12]
Compiling with GTK left on causes a "gtk_text_view_set_attributes_from_style" - exception at startup:

> Program` received signal SIGSEGV, Segmentation fault.
> gtk_text_view_set_attributes_from_style (text_view=0x12c16c0, style=0x1278820, values=0x0) at /build/gtk+2.0-3ongxb/gtk+2.0-2.24.23/gtk/gtktextview.c:6380
> 6380    /build/gtk+2.0-3ongxb/gtk+2.0-2.24.23/gtk/gtktextview.c: File not found.

**Comment by jonof** [comment]
Does the master branch work now? (commit 54912c4)

**Comment by BenjiClub** [comment]
It still crashes

**Comment by BenjiClub** [comment]
I get now a compile error:
startgtk.game.c:(.text+0x2781): undefined reference to `gtk_main_iteration'
startgtk.game.c:(.text+0x2786): undefined reference to `gtk_events_pending'
src/startgtk.game.o: In Funktion `startwin_idle':
startgtk.game.c:(.text+0x2a51): undefined reference to `gtk_main_iteration'
startgtk.game.c:(.text+0x2a56): undefined reference to `gtk_events_pending'

**Comment by BenjiClub** [comment]
Ah, ok, I had to add GAMELIBS= $(shell pkg-config --libs gtk+-2.0) it compiles now ... But still throws a segmentation fault...

```
Program received signal SIGSEGV, Segmentation fault.
gtk_text_view_set_attributes_from_style (text_view=0x12b96c0, style=0x126e820, values=0x0)
    at /build/gtk+2.0-KsZSEA/gtk+2.0-2.24.23/gtk/gtktextview.c:6380
6380	/build/gtk+2.0-KsZSEA/gtk+2.0-2.24.23/gtk/gtktextview.c: Datei oder Verzeichnis nicht gefunden.
```

**Comment by BenjiClub** [comment]
I tried it and it doesn't compile.
I googled it and it seems to be a theme problem.
Oxygen theme seems to make some problems. Is it the theme active?

**Comment by BenjiClub** [comment]
The gtk-oxygen theme seems to make trouble. I've switched the desktop environment and it now works.
