### ISSUE TITLE
Windows 10 issue

### ISSUE THREAD

**Issue by lsudotnet** [jonof/jfsw#22]
Just built with Win10 / MSVC 2017 Community Edition.

Mouse turning doesn't seem to work.  Any ideas?

**Comment by jonof** [comment]
I can't verify with my Windows machine at the moment because it's on loan to a friend, but I suggest checking that the mouse analogue axis settings are sensible in sw.cfg. They should appear as below by default:
```
MouseAnalogAxes0 = "analog_turning"
MouseAnalogScale0 = 65536
MouseAnalogAxes1 = "analog_moving"
MouseAnalogScale1 = 65536
```

**Comment by lsudotnet** [comment]
Those configuration lines exist within sw.cfg.

**Comment by lsudotnet** [comment]
Reporting new issue; after alt-tab out and back in mouse turning stops working on Windows.
