### ISSUE TITLE
No music in RetroPie

### ISSUE THREAD

**Issue by DrBuns3n** [jonof/jfsw#25]
I compiled jfsw on a Pi4 running RetroPie 4.7, but although there's sound effects, the music is not playing. 

I copied the MUSIC folder to the jfsw folder on my Pi. I understand JFSW expects the music tracks to be in the same folder as the binary so I edited the config file, /home/pi/.jfsw/sw.cfg and added the music folder as below:

OggTrackName = "MUSIC/track??.ogg"

I also tried the default location for the music tracks and reverted the sw.cfg file, but that didn't make any difference.

**Comment by jonof** [comment]
I suggest first verifying that the game was built with Ogg Vorbis support by running this command at a terminal: `ldd /path/to/jfsw/sw | grep -E 'ogg|vorbis'`

You should see output like:
```
$ ldd sw | grep -E 'ogg|vorbis'
        libvorbisfile.so.3 => /usr/lib/.../libvorbisfile.so.3 (0x.....)
        libvorbis.so.0 => /usr/lib/.../libvorbis.so.0 (0x.....)
        libogg.so.0 => /usr/lib/.../libogg.so.0 (0x.....)
```
If you don't see that, you'll want to install the _libvorbis-dev_ package and use `make clean sw` to recompile.
If you do see output like above, then something else is going on and I'll try to think of what it could be.

**Comment by s1eve-mcdichae1** [comment]
Posting to this issue instead of starting a new one since I also am having music issues on RetroPie.

Should there be MIDI music if I don't have the OGG tracks? The OGG tracks do work if I have them, I'm just trying to do it without them, if that is even possible.

I have built with:

    make DATADIR="/home/pi/RetroPie/roms/ports/shadowwarrior" RELEASE=1 USE_POLYMOST=1 USE_OPENGL=USE_GLES2 WITHOUT_GTK=1

SFX and Ambience work. OGG music works if tracks are present in DATADIR. No music at all if OGG tracks are not present.

I've tried building and playing both with and without `libfluidsynth-dev` installed. When it was installed, launching the game took a bit longer as it scrolled through some kind of ("socket failure"? I forget exactly) errors but it eventually did load, but there still wasn't any music. Other possibly-relevant packages I have installed are: `libgl1-mesa-dev libsdl2-dev libvorbis-dev timidity freepats`

I'm on Raspberry Pi 4 using Raspbian/Debian 10 lite (terminal, no X/desktop environment.)

**Comment by jonof** [comment]
The Registered version `sw.grp` doesn't provide MIDI music. Only the Shareware version has it.

**Comment by s1eve-mcdichae1** [comment]
> The Registered version `sw.grp` doesn't provide MIDI music. Only the Shareware version has it.

Ah, I did not know that, however I still am getting no music even with the shareware version. I have a console log, if it helps. I see these "cannot connect to server socket err" but I don't know what they mean:

```
Parameters: 
Executing: /opt/retropie/ports/jfsw/sw ""
fluidsynth: warning: Failed to pin the sample data to RAM; swapping is possible.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
exec of JACK server (command = "/usr/bin/jackd") failed: No such file or directory
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
fluidsynth: error: Failed to connect to Jack server.
Added /home/pi/RetroPie/roms/ports/shadowwarrior/ to search path.
Added /opt/retropie/ports/jfsw/ to search path.
Added /home/pi/.jfsw/ to search path.

JFShadowWarrior
Based on Shadow Warrior by 3D Realms Entertainment.
Additional improvements by Jonathon Fowler (http://www.jonof.id.au) and other contributors.
See GPL.TXT for license terms.

Version 20211225.
Built Mar 14 2022 00:56:09.

BUILD engine by Ken Silverman (http://www.advsys.net/ken)
Additional improvements by Jonathon Fowler (http://www.jonof.id.au)
and other contributors. See BUILDLIC.TXT for terms.

Version ab02edc.
Built Mar 14 2022 00:56:15 using GCC 8.3.
32-bit word size.

SDL2 system interface (compiled with SDL version 2.0.10, runtime version 2.0.10)
Loading system OpenGL library
Detecting video modes:
  - 1280x720 8-bit fullscreen
  - 800x600 8-bit fullscreen
  - 640x480 8-bit fullscreen
  - 640x400 8-bit fullscreen
  - 512x384 8-bit fullscreen
  - 480x360 8-bit fullscreen
  - 400x300 8-bit fullscreen
  - 320x240 8-bit fullscreen
  - 320x200 8-bit fullscreen
  - 1280x720 32-bit fullscreen
  - 800x600 8-bit windowed
  - 640x480 8-bit windowed
  - 640x400 8-bit windowed
  - 512x384 8-bit windowed
  - 480x360 8-bit windowed
  - 400x300 8-bit windowed
  - 320x240 8-bit windowed
  - 320x200 8-bit windowed
  - 800x600 32-bit windowed
  - 640x480 32-bit windowed
  - 640x400 32-bit windowed
  - 512x384 32-bit windowed
  - 480x360 32-bit windowed
  - 400x300 32-bit windowed
  - 320x240 32-bit windowed
  - 320x200 32-bit windowed
Scanning for GRP files...
GRP file: sw.grp
Detected shareware GRP

SHADOW WARRIOR(tm) (Shareware Version)
Copyright (c) 1997 3D Realms Entertainment

Game controllers:
  - Logitech F710 Gamepad (XInput)
Using controller Logitech F710 Gamepad (XInput)
CONTROL_Startup: Mouse Present
CONTROL_Startup: Joystick Present
Initialising timer
Loading sound and graphics...
initcache(): Initialised with 33554416 bytes
Setting video mode 640x480 (8-bpp fullscreen)
FX_Init: trying SDL
SDLDrv: audio driver: alsa
FX driver is SDL
CD_Init: trying SDL
MUSIC_Init: trying FluidSynth
FluidSynthDrv: using version 1.1.11, built with 1.1.11
FluidSynthDrv: using found soundfont /usr/share/sounds/sf2/FluidR3_GM.sf2
Music driver is FluidSynth
PolymostTexCache: cache index unloaded
```

**Comment by jonof** [comment]
FluidSynth tries to use the JACK output driver by default. With FluidSynth version 1.1 you would need to tell it to use ALSA or PulseAudio instead via the `~/.jfsw/sw.cfg` file, e.g.

    [Sound Setup]
    MusicParams = "audio.driver=pulseaudio"
    FXDevice = 0
    ...

**Comment by s1eve-mcdichae1** [comment]
@jonof this worked with `"audio.driver=alsa"`, thanks.
