### ISSUE TITLE
Fails to compile on Linux (Fedora 35) src/driver_alsa.c:29:10: fatal error: asoundlib.h: No such file or directory

### ISSUE THREAD

**Issue by mcossey** [jonof/jfsw#32]
commit 3d82a71dc7bec1b404978e52c801b449db4d11a5

I was able to fix this by changing driver_alsa.c:29 from `#include <asoundlib.h>` to `#include <alsa/asoundlib.h>`.

I've no great talent at this sort of thing so this may be a red herring but I found something that suggests this is because of a change from alsa 1.1.8 to 1.1.9 https://alsa-project.org/wiki/Changes_v1.1.8_v1.1.9

**Comment by jonof** [comment]
I wondered when that deprecation would eventually bite me, but it's apparently not ALSA that's removed the backwards-compatibility header file, so Fedora must have an ALSA imitation package. Either way, jonof/jfaudiolib@474e0c6890f21e3754f00e0aee61b11987ae9842 updates the path and the submodule here in JFSW will be updated soon.
