### ISSUE TITLE
Right analog stick not working correctly

### ISSUE THREAD

**Issue by jeffkrull** [jonof/jfsw#34]
I've just installed JFSW on RetroPie on my Raspberry Pi 4 using the RetroPie-Extras install script, and everything works. I'm able to get .OGG audio running, and both expansions work correctly as well as the main game. However, I'm having a lot of trouble mapping controls. 

I'm playing using my 8bitdo SN30 Pro Wired controller, which maps as an Xinput device (Xbox 360 controller). The face buttons and D-pad all map correctly, as well as the LB and RB buttons. However, none of the other buttons map as they should. In the configuration menu, L3 is actually Start, Back is actually LT/L2, Guide is actually Back/Select, and Start is actually RT/R2. On top of that, the right analog stick is completely broken. The RightY axis is always mapped to Strafe, even if I unset the configuration in the menu, and the RightX axis does nothing. The LeftTrigger and RightTrigger axes do nothing either. I don't think this is an issue with my controller, as jstest shows the axes working correctly, and it works in other games I play like lzdoom.

**Comment by jonof** [comment]
Try grabbing a copy of https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txt and putting it alongside the _sw.grp_ file and see if that improves things.

**Comment by jeffkrull** [comment]
Thanks for the suggestion. I added the file to the three possible places RetroPie could possibly work (/opt/retropie/ports/jfsw/ alongside the sw executable, /opt/retropie/configs/ports/sw/ alongside the sw.cfg file, and /home/RetroPie/roms/ports/shadowwarrior/ alongside sw.grp), and it had no effect.

**Comment by jeffkrull** [comment]
I finally figured out that my problem was entirely with the SDL mapping for the 8bitdo controller. It's not listed in the gamecontrollerdb.txt. I determined the SDL mapping, and now all buttons work properly. This is a non-issue. Thank you for your help.
