### ISSUE TITLE
original retail MacOS group not detected as registered

### ISSUE THREAD

**Issue by classilla** [jonof/jfsw#36]
The `SW Group` file from the retail Lion classic MacOS port shows up as `Mac Registered Version` but starts as shareware, even if named `swmac.grp`. I had to manually change it to `GRPFILE_GAME_SWSW` in `src/grpscan.c` to get it to start registered.

**Comment by jonof** [comment]
Seems I'm a fool who didn't notice he wrote "GRPFILE_GAME_SW" instead of "GRPFILE_GAME_SWSW" on these lines: https://github.com/jonof/jfsw/blob/master/src/game.h#L53-L54

**Comment by classilla** [comment]
No worries! Thanks much for the great port. Zilla sends his regards.
