### ISSUE TITLE
Can't get mouse to turn left and right

### ISSUE THREAD

**Issue by parkerlreed** [jonof/jfsw#8]
Setting digital up to turn left and digital down to turn right kinda works but doesnt feel like it should. Looking up and down works great just not turning.

Arch x86_64

**Comment by BenjiClub** [comment]
Any progress on this point?

**Comment by jonof** [comment]
I'll close this on the assumption it's improved by more recent changes. For the record though, in sw.cfg the MouseAnalogAxes0 setting should be "analog_turning" and MouseAnalogAxes1 should be "analog_moving". The digital axes should have "" values.

**Comment by parkerlreed** [comment]
Thanks. It's been so long since I had tried and submitted this. Thanks for the response.

**Comment by orbea** [comment]
I compiled jfsw from the git master and ran into this too, adding "analog_turning" and "analog_moving" as described above fixed it for me, thanks.
